Fix NPE when referencing missing maven_jar target.
This is because the fingerprint generator expects some data to fingerprint. And
there is no check of null any place in the stack that crashes:

java.lang.RuntimeException: Unrecoverable error while evaluating node
'REPOSITORY:@org.apache.thrift_libthrift' (requested by nodes 'PACKAGE_LOOKUP:@org.apache.thrift_libthrift//jar')
  at
  com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:982)
  at
  com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
  at
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  Caused by: java.lang.NullPointerException
  at
  java.security.MessageDigest.update(MessageDigest.java:335)
  at
  com.google.devtools.build.lib.util.Fingerprint.addBytes(Fingerprint.java:116)
  at
  com.google.devtools.build.lib.rules.repository.RepositoryFunction.computeRuleKey(RepositoryFunction.java:116)
  at
  com.google.devtools.build.lib.rules.repository.RepositoryFunction.isFilesystemUpToDate(RepositoryFunction.java:183)
  at
  com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:104)
  at
  com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:933)
  ... 4 more

Change-Id: I39bfc5c40f02198ddcf1c3da3c333e20c15ece97