Fix broken Bazel build due to missing dependency.
ERROR: /home/ci/workspace/Bazel/JAVA_VERSION/1.8/PLATFORM_NAME/linux-x86_64/src/main/java/com/google/devtools/build/lib/BUILD:404:1: Couldn't build file src/main/java/com/google/devtools/build/lib/libjava-toolchain-parser.jar: Java compilation in rule '//src/main/java/com/google/devtools/build/lib:java-toolchain-parser' failed: namespace-sandbox failed: error executing command /home/ci/.cache/bazel/_bazel_ci/5f3cd5a16c8c04003810da50910b348c/linux-x86_64/_bin/namespace-sandbox ... (remaining 8 argument(s) skipped).
src/main/java/com/google/devtools/build/lib/rules/java/JavaToolchainData.java:40: error: [strict] Using type javax.annotation.Nullable from an indirect dependency (TOOL_INFO: "//third_party:jsr305"). See command below **
  @Nullable private final Iterable<String> bootclasspath;
   ^
1 error
** Please add the following dependencies:
  //third_party:jsr305  to //src/main/java/com/google/devtools/build/lib:java-toolchain-parser

--
MOS_MIGRATED_REVID=115559988