The legal workspace name rule was way too strict.
Replacing it with a (much longer), but more permissive rule, accepting '-'
and '.' in names, but require the first character to be alphanumeric.

Respect maven excludes and separate build rules.

Updating the generate_workspace tool to:

 - Respect dependency exclutions from the project object model (maven).

 - Generate one rule per pom dependency or maven_jar source rule (using maven
   group ID and artifact ID).

Change-Id: Ieb878f82be4352dcfb5755f8f71dfa7e592de78a

Load unix library from within _deploy.jar

Change-Id: Ib61409d96190499aa97aabd1c837b1a2cac77b7a

Strip content of *.sha1 if containing filename.

Sometimes the sha1 file contains the filename that it hashed (it's not
supposed to, but sometimes it still does).

Change-Id: I680f11ab5c5c0387c3fbd1106030e71cbe38d5c0

Resolve test scope dependencies in own pom.xml.

Resolve the test scope dependencies from the directly targeted pom.xml files, so
test dependencies also get into the BUILD file.

Marking generated test dependencies as testonly=1.

Change-Id: Ib26222f7f1a2cd68523413922c296d39636b6af5

Fix NPE when referencing missing maven_jar target.

This is because the fingerprint generator expects some data to fingerprint. And
there is no check of null any place in the stack that crashes:

java.lang.RuntimeException: Unrecoverable error while evaluating node
'REPOSITORY:@org.apache.thrift_libthrift' (requested by nodes 'PACKAGE_LOOKUP:@org.apache.thrift_libthrift//jar')
  at
  com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:982)
  at
  com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
  at
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  Caused by: java.lang.NullPointerException
  at
  java.security.MessageDigest.update(MessageDigest.java:335)
  at
  com.google.devtools.build.lib.util.Fingerprint.addBytes(Fingerprint.java:116)
  at
  com.google.devtools.build.lib.rules.repository.RepositoryFunction.computeRuleKey(RepositoryFunction.java:116)
  at
  com.google.devtools.build.lib.rules.repository.RepositoryFunction.isFilesystemUpToDate(RepositoryFunction.java:183)
  at
  com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:104)
  at
  com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:933)
  ... 4 more

Change-Id: I39bfc5c40f02198ddcf1c3da3c333e20c15ece97

Sort everything.